package com.atlassian.performance.tools.virtualusers

import java.time.Duration
import java.util.*

/**
 * Describes load for performance test.
 *
 * @param virtualUsersPerNode number of virtual users to run per node
 * @param loadDuration of the load generated by virtual users
 * @param rampUpInterval between virtual users within a node
 * @param seed random seed to be used by virtual users
 */
data class VirtualUserLoad(
    val virtualUsersPerNode: Int = 1,
    val loadDuration: Duration = Duration.ofMinutes(5),
    val rampUpInterval: Duration = Duration.ofSeconds(0),
    val seed: Long = Random().nextLong()
)