name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? yes/no'
        default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle') }}
      - name: Fix Docker-In-Docker mounts # https://github.com/moby/moby/issues/13742#issuecomment-725197223
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
      - name: Build
        run: ./gradlew build
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests
      - name: Get publish token
        id: publish-token
        if: github.event.inputs.release == 'yes'
        uses: atlassian-labs/artifact-publish-token@v1.0.1
      - name: Release
        if: github.event.inputs.release == 'yes'
        env:
          atlassian_private_username: ${{ steps.publish-token.outputs.artifactoryUsername }}
          atlassian_private_password: ${{ steps.publish-token.outputs.artifactoryApiKey }}
        run: |
          ./gradlew release -Prelease.customUsername=${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ./gradlew publish
